name: 🐞 Bug Report
description: Report a problem or unexpected behavior in Logic Lab Circuit
title: "[Bug]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report for Logic Lab Circuit
        Please help us improve the app by reporting bugs you encounter during your logic circuit simulations.

  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise explanation of the issue.
      placeholder: e.g., The AND gate does not update when inputs change
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a step-by-step guide to trigger the bug.
      placeholder: |
        1. Open Logic Lab Circuit
        2. Add an AND gate to the canvas
        3. Set Input A to true and Input B to false
        4. Output remains unchanged

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: textarea
    id: media
    attributes:
      label: Screenshots / Video (if available)
      description: Drag and drop screenshots or recordings that show the bug.

  - type: input
    id: environment
    attributes:
      label: Device & Environment
      description: Provide info like your device model, iOS version, and app version.
      placeholder: e.g., iPhone 15, iOS 17.5.1, Logic Lab Circuit 1.0.1

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might help us reproduce or understand the issue.
